"use client";
import { useState } from "react";
import { Check, LoaderCircle } from "lucide-react";
import { useRouter } from "next/navigation";
type Props = { weekStart: string; autoWins: string; autoMisses: string; autoRisks: string; existing?: { causes?: string | null; pauseOrStop?: string | null; top3?: string | null; notes?: string | null } };
type Envelope = { ok: boolean; error?: { message?: string } };
export function WeeklyReviewComposer({ weekStart, autoWins, autoMisses, autoRisks, existing }: Props) {
  const router = useRouter(); const [causes, setCauses] = useState(existing?.causes ?? ""); const [pause, setPause] = useState(existing?.pauseOrStop ?? ""); const [top3, setTop3] = useState(existing?.top3 ?? ""); const [notes, setNotes] = useState(existing?.notes ?? ""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function save() { if (!top3.trim()) { setError("Définis les principales priorités de la semaine suivante."); return; } setSaving(true); setError(null); try { const response = await fetch("/api/data/weekly_reviews", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ week_start: weekStart, wins: autoWins, misses: autoMisses, causes: causes || null, risks: autoRisks || null, pause_or_stop: pause || null, next_week_top3: top3, notes: notes || null }) }); const result = await response.json() as Envelope; if (!response.ok || !result.ok) throw new Error(result.error?.message || "Enregistrement impossible."); setMessage("Semaine suivante préparée."); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Enregistrement impossible."); } finally { setSaving(false); } }
  return <section className="card grid gap-4"><div><h2 className="text-lg font-bold">Préparer la semaine suivante</h2><p className="mt-1 text-sm text-slate-600">Les faits ci-dessus sont automatiques. Note seulement les arbitrages.</p></div><div className="grid gap-4 lg:grid-cols-2"><label className="field">Contexte utile (optionnel)<textarea className="input min-h-20" value={causes} onChange={(event) => setCauses(event.target.value)} /></label><label className="field">À réduire / mettre en pause (optionnel)<textarea className="input min-h-20" value={pause} onChange={(event) => setPause(event.target.value)} /></label></div><label className="field">Priorités de la semaine suivante *<textarea className="input min-h-24" value={top3} onChange={(event) => setTop3(event.target.value)} placeholder={"1. …\n2. …\n3. …"} /></label><details className="rounded-2xl border border-slate-200 bg-slate-50/60 p-3"><summary className="cursor-pointer text-sm font-bold">Note libre facultative</summary><textarea className="input mt-3 min-h-20" value={notes} onChange={(event) => setNotes(event.target.value)} /></details>{error ? <p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}{message ? <p className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900"><Check size={17} />{message}</p> : null}<div><button className="button-primary" disabled={saving} onClick={() => void save()}>{saving ? <LoaderCircle className="animate-spin" size={17} /> : <Check size={17} />}{saving ? "Enregistrement…" : "Valider la préparation"}</button></div></section>;
}
